# Warp Launch Configuration
#
#
# Use this to start a certain configuration of windows, tabs, and panes.
# Open the launch configuration palette to access and open any launch configuration.
#
# This file defines your launch configuration.
# More on how to do so here:
# https://docs.warp.dev/features/session-management/launch-configurations
#
# All launch configurations are stored under ~/.local/share/warp-terminal/launch_configurations.
# Edit them anytime!
#
# You can also add commands that run on-start for your launch configurations like so:
# ---
# name: Example with Command
# windows:
#  - tabs:
#      - layout:
#          cwd: /Users/warp-user/project
#          commands:
#            - exec: code .

---
name: Hippolyte
windows:
  - tabs:
      - title: 🎨 Storybook
        layout:
          split_direction: horizontal
          panes:
            - cwd: /home/paco/dev/hippolyte-ui
            - split_direction: vertical
              panes:
                - cwd: /home/paco/dev/sourcing
                - cwd: /home/paco/dev/hippolyte-ui
        color: magenta
      - title: 🌐 SSH
        layout:
          cwd: ""
        color: blue
      - title: 💻 Dev
        layout:
          split_direction: horizontal
          panes:
            - split_direction: vertical
              panes:
                - cwd: /home/paco/dev/hippolyte-candidate
                - cwd: /home/paco/dev/hippolyte-candidate
            - split_direction: vertical
              panes:
                - cwd: /home/paco/dev/conciliator
                - cwd: /home/paco/dev/conciliator
        color: green
